spring:
  application:
    name: movieflix

  datasource:
    url: jdbc:postgresql://localhost:5433/movieflix
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html

movieflix:
  security:
      secret: "cbf29ce484222325"
